Lglen/server
golemfactory/webcomputing pull request #1
Opened 2020-09-23 19:29 UTC by lukasz-glen

The web server for WC4G.

The first version of the web server. 
It still lacks some functionality but it allows computations in a web browser.
Tested on Firefox.
Synchronization part requires rewriting in the future.

2020-09-24 08:50 UTC, kubkon requested changes
Looks great! I've got a couple of comments though.

2020-09-24 08:50 UTC, kubkon commented on server/src/main.rs
> +    tasks_map.insert(task_id, TaskStatus::Enqueued);
In order to release the lock immediately after inserting `task_id` and `TaskStatus::Enqueued` into the hash map, you can combine these two lines into one like so:

```rust
TASKS.lock().unwrap().insert(task_id, TaskStatus::Enqueued);
```

2020-09-24 08:50 UTC, kubkon commented on server/src/main.rs
> +    fs::create_dir(format!("./task/{}/input", rand_string))?;
In order to make the paths OS-agnostic, you should use `std::path::Path` instead of raw `String`s like so:

```rust
use std::path::Path;

fs::create_dir(Path::new("task").join(&rand_string))?;
fs::create_dir(Path::new("task").join(&rand_string).join("input"))?;
```

This will generate OS-appropriate paths for the platform you're compiling for.

2020-09-24 08:50 UTC, kubkon commented on server/src/main.rs
> +    while let Ok(Some(mut field)) = payload.try_next().await {
We don't handle errors here. Is this by design?

2020-09-24 08:50 UTC, kubkon commented on server/src/main.rs
> +    while let Ok(Some(mut field)) = payload.try_next().await {
Wouldn't

```rust
while let Some(mut field) = payload.try_next().await? {
```

be more appropriate here?

2020-09-24 08:50 UTC, kubkon commented on server/src/main.rs
> +    let task_status = tasks_map.get(&task_id);
You can limit the duration of the lock by combining the two ops into one like so:

```rust
let task_status = TASKS.lock().unwrap().get(&task_id);
```

Because `TaskStatus` is `Copy`, this should automatically create a copy of `TaskStatus` and call `Drop` on the mutex lock.

2020-09-24 08:50 UTC, kubkon commented on server/src/main.rs
> +    Ok(NamedFile::open(format!("task/{}/input/{}", task_id, file_name))?)
Use `std::path::Path` to make it OS-agnostic like so:

```rust
use std::path::Path;

NamedFile::open(Path::new("task").join(task_id).join("input").join(file_name))?
```

2020-09-24 08:50 UTC, kubkon commented on server/src/main.rs
> +                while let Ok(Some(mut field)) = payload.try_next().await {
Like below, shouldn't we handle here error explicitly:

```rust
while let Some(mut field) = payload.try_next().await? {
```

2020-09-24 08:50 UTC, kubkon commented on server/src/main.rs
> +                    let filepath = format!("./task/{}/result/{}", &task_id, sanitize_filename::sanitize(&filename));
Use `std::path::Path::join` instead of raw `String`s here.

2020-09-24 08:50 UTC, kubkon commented on server/src/main.rs
> +                        let data = chunk.unwrap();
In general, `unwrap`s should never be used unless you've explicitly made sure they will not trigger a runtime panic (or in other words, much like in C, use them as asserts for conditions that are unexpected and fatal). Note that this does not apply to acquiring the mutex lock for instance as it is idiomatic to call `Mutex.lock().unwrap()`.

2020-09-24 08:50 UTC, kubkon commented on server/src/main.rs
> +    match status {
I think we don't really need to keep the lock already here, so we could rewrite this bit as

```rust
match TASKS.lock().unwrap().get(&task_id) {
```

2020-09-24 08:50 UTC, kubkon commented on server/src/main.rs
> +                tasks_map.insert(task_id.clone(), TaskStatus::Completed);
Acquire the lock only for the duration of insertion here like so:

```rust
TASKS.lock().unwrap().insert(task_id.clone(), TaskStatus::Completed);
```

2020-09-24 08:50 UTC, kubkon commented on server/src/main.rs
> +    }
To limit the scope of the mutex in this bit, you can wrap this bit of code in an explicit block:

```rust
let d = {
    let mut tasks_map = TASKS.lock().unwrap();
    let mut out = String::new();
    for key in tasks_map.keys() {
        let value = tasks_map.get(key);
        match tasks_map.get(key) {
            Some(v) if *v == TaskStatus::Enqueued => {
                 out = key.clone();
                 break;
            }
            else => continue,
        }
    }
    out
};
```

2020-09-24 08:50 UTC, kubkon commented on server/src/main.rs
> +        tasks_map.insert(d.clone(), TaskStatus::Failed);
Acquire the mutex only for the duration of insertion into the map:

```rust
TASKS.lock().unwrap().insert(d.clone(), TaskStatus::Failed);
```

2020-09-24 08:50 UTC, kubkon commented on server/src/main.rs
> +                if (*e).to_str().unwrap() == "wasm" {
This `unwrap` should really be handled gracefully here.

2020-09-24 08:50 UTC, kubkon commented on server/src/main.rs
> +                    tasks_map.insert(d.clone(), TaskStatus::Sent);
Same here for the mutex:

```rust
TASKS.lock().unwrap().insert(d.clone(), TaskStatus::Sent);
```

2020-09-24 08:50 UTC, kubkon commented on server/src/main.rs
> +    tasks_map.insert(d.clone(), TaskStatus::Failed);
And here:

```rust
TASKS.lock().unwrap().insert(d.clone(), TaskStatus::Failed);
```

2020-09-24 08:50 UTC, kubkon commented on server/src/main.rs
> +use std::path::Path;
Could you run `cargo fmt` from the root of the crate? This will nicely reformat all relevant Rust source files :-)

2020-09-24 18:37 UTC, lukasz-glen commented on server/src/main.rs
> +    tasks_map.insert(task_id, TaskStatus::Enqueued);
Actually it does not change much. Right after is a return instruction which creates a plain object.
Anyway, done.

2020-09-24 18:50 UTC, lukasz-glen commented on server/src/main.rs
> +    fs::create_dir(format!("./task/{}/input", rand_string))?;
done

2020-09-24 18:59 UTC, lukasz-glen commented on server/src/main.rs
> +    let task_status = tasks_map.get(&task_id);
The compile error for the above is
```creates a temporary which is freed while still in use```
It is because `task_status` is `borrow` and `later used`. 
I am not sure if it actually creates a copy.
Anyway, the next instruction is a plain return, so I can leave it as it is.

2020-09-24 19:02 UTC, lukasz-glen commented on server/src/main.rs
> +    Ok(NamedFile::open(format!("task/{}/input/{}", task_id, file_name))?)
done

2020-09-24 19:06 UTC, lukasz-glen commented on server/src/main.rs
> +                    let filepath = format!("./task/{}/result/{}", &task_id, sanitize_filename::sanitize(&filename));
done

2020-09-24 19:11 UTC, lukasz-glen commented on server/src/main.rs
> +use std::path::Path;
done

2020-09-24 20:07 UTC, lukasz-glen commented on server/src/main.rs
> +                if (*e).to_str().unwrap() == "wasm" {
Corrected. Please see if it is ok.

2020-09-25 09:08 UTC, lukasz-glen commented on server/src/main.rs
> +                        let data = chunk.unwrap();
done
but I would like to know what kind of errors it can be

2020-09-25 09:13 UTC, lukasz-glen commented on server/src/main.rs
> +    while let Ok(Some(mut field)) = payload.try_next().await {
it was copied from [actix tutorial](https://github.com/actix/examples/blob/master/multipart/src/main.rs)
done
but I would ask for the explanation: what does the previous code do, does it do unwrap?

2020-09-25 09:15 UTC, lukasz-glen commented on server/src/main.rs
> +                while let Ok(Some(mut field)) = payload.try_next().await {
done

2020-09-25 09:22 UTC, lukasz-glen commented on server/src/main.rs
> +    match status {
the same here, a trouble with borrowing
maybe I should copy status manually?

2020-09-25 09:23 UTC, lukasz-glen commented on server/src/main.rs
> +                tasks_map.insert(task_id.clone(), TaskStatus::Completed);
will not fix this until the above is fixed

2020-09-25 09:29 UTC, kubkon commented on server/src/main.rs
> +    let task_status = tasks_map.get(&task_id);
Oh shoot, sorry, I forgot to say you also need to dereference the result of `get`, so it should look as follows:

```rust
let task_status = *TASKS.lock().unwrap().get(&task_id);
```

2020-09-25 09:34 UTC, kubkon commented on server/src/main.rs
> +    match status {
If a type is `Copy`, to trigger a copy from a reference (`get` method will actually return a maybe-reference `Option<&T>`), you should use a dereference operator `*`. In this case I think you should dereference when destructuring the optional

```rust
match TASKS.lock().unwrap().get(&task_id) {
    Some(*s) => {
    }
    None => {}
}
```

2020-09-25 09:58 UTC, lukasz-glen commented on server/src/main.rs
> +    }
done and I added some improvement here

2020-09-25 09:58 UTC, lukasz-glen commented on server/src/main.rs
> +        tasks_map.insert(d.clone(), TaskStatus::Failed);
done

2020-09-25 09:58 UTC, lukasz-glen commented on server/src/main.rs
> +                    tasks_map.insert(d.clone(), TaskStatus::Sent);
moved and done

2020-09-25 09:58 UTC, lukasz-glen commented on server/src/main.rs
> +    tasks_map.insert(d.clone(), TaskStatus::Failed);
done

2020-09-25 11:38 UTC, lukasz-glen commented on server/src/main.rs
> +                tasks_map.insert(task_id.clone(), TaskStatus::Completed);
corrected

2020-09-25 11:42 UTC, lukasz-glen commented
Almost every comment is addressed. The one not addressed are synchronization related and do not need further improvements as locks are very short time lived.

2020-09-25 12:26 UTC, kubkon approved these changes
LGTM!

2020-09-25 12:26 UTC, merged